/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.calculadora1;



/**
 *
 * @author carlo
 */
public class CalculadoraFrame extends Calculadora {
    

    /**
     * Creates new form CalculadoraFrame
     */
    public CalculadoraFrame() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Principal = new javax.swing.JPanel();
        Result = new javax.swing.JLabel();
        borrar = new javax.swing.JButton();
        siete = new javax.swing.JButton();
        ocho = new javax.swing.JButton();
        nueve = new javax.swing.JButton();
        dividir = new javax.swing.JButton();
        cuatro = new javax.swing.JButton();
        cinco = new javax.swing.JButton();
        seis = new javax.swing.JButton();
        por = new javax.swing.JButton();
        uno = new javax.swing.JButton();
        cero = new javax.swing.JButton();
        igual = new javax.swing.JButton();
        mas = new javax.swing.JButton();
        dos = new javax.swing.JButton();
        tres = new javax.swing.JButton();
        menos = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Principal.setBackground(new java.awt.Color(51, 51, 51));
        Principal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Result.setBackground(new java.awt.Color(51, 51, 51));
        Result.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        Result.setForeground(new java.awt.Color(255, 255, 255));
        Result.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Result.setOpaque(true);
        Principal.add(Result, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 31, 332, 61));

        borrar.setBackground(new java.awt.Color(204, 204, 204));
        borrar.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        borrar.setText("C");
        borrar.setBorder(null);
        borrar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        borrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borrarActionPerformed(evt);
            }
        });
        Principal.add(borrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 60, 60));

        siete.setBackground(new java.awt.Color(102, 102, 102));
        siete.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        siete.setForeground(new java.awt.Color(255, 255, 255));
        siete.setText("7");
        siete.setBorder(null);
        siete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sieteActionPerformed(evt);
            }
        });
        Principal.add(siete, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 60, 60));

        ocho.setBackground(new java.awt.Color(102, 102, 102));
        ocho.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        ocho.setForeground(new java.awt.Color(255, 255, 255));
        ocho.setText("8");
        ocho.setBorder(null);
        ocho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ochoActionPerformed(evt);
            }
        });
        Principal.add(ocho, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 180, 60, 60));

        nueve.setBackground(new java.awt.Color(102, 102, 102));
        nueve.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        nueve.setForeground(new java.awt.Color(255, 255, 255));
        nueve.setText("9");
        nueve.setBorder(null);
        nueve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nueveActionPerformed(evt);
            }
        });
        Principal.add(nueve, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 180, 60, 60));

        dividir.setBackground(new java.awt.Color(255, 153, 0));
        dividir.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        dividir.setForeground(new java.awt.Color(255, 255, 255));
        dividir.setText("/");
        dividir.setBorder(null);
        dividir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dividirActionPerformed(evt);
            }
        });
        Principal.add(dividir, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, 60, 60));

        cuatro.setBackground(new java.awt.Color(102, 102, 102));
        cuatro.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        cuatro.setForeground(new java.awt.Color(255, 255, 255));
        cuatro.setText("4");
        cuatro.setBorder(null);
        cuatro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cuatroActionPerformed(evt);
            }
        });
        Principal.add(cuatro, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 60, 60));

        cinco.setBackground(new java.awt.Color(102, 102, 102));
        cinco.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        cinco.setForeground(new java.awt.Color(255, 255, 255));
        cinco.setText("5");
        cinco.setBorder(null);
        cinco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cincoActionPerformed(evt);
            }
        });
        Principal.add(cinco, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 250, 60, 60));

        seis.setBackground(new java.awt.Color(102, 102, 102));
        seis.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        seis.setForeground(new java.awt.Color(255, 255, 255));
        seis.setText("6");
        seis.setBorder(null);
        seis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seisActionPerformed(evt);
            }
        });
        Principal.add(seis, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 250, 60, 60));

        por.setBackground(new java.awt.Color(255, 153, 0));
        por.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        por.setForeground(new java.awt.Color(255, 255, 255));
        por.setText("X");
        por.setBorder(null);
        por.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                porActionPerformed(evt);
            }
        });
        Principal.add(por, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 110, 60, 60));

        uno.setBackground(new java.awt.Color(102, 102, 102));
        uno.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        uno.setForeground(new java.awt.Color(255, 255, 255));
        uno.setText("1");
        uno.setBorder(null);
        uno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unoActionPerformed(evt);
            }
        });
        Principal.add(uno, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 60, 60));

        cero.setBackground(new java.awt.Color(102, 102, 102));
        cero.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        cero.setForeground(new java.awt.Color(255, 255, 255));
        cero.setText("0");
        cero.setBorder(null);
        cero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ceroActionPerformed(evt);
            }
        });
        Principal.add(cero, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, 240, 60));

        igual.setBackground(new java.awt.Color(255, 153, 0));
        igual.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        igual.setForeground(new java.awt.Color(255, 255, 255));
        igual.setText("=");
        igual.setBorder(null);
        igual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                igualActionPerformed(evt);
            }
        });
        Principal.add(igual, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 320, 60, 130));

        mas.setBackground(new java.awt.Color(255, 153, 0));
        mas.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        mas.setForeground(new java.awt.Color(255, 255, 255));
        mas.setText("+");
        mas.setBorder(null);
        mas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                masActionPerformed(evt);
            }
        });
        Principal.add(mas, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 180, 60, 130));

        dos.setBackground(new java.awt.Color(102, 102, 102));
        dos.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        dos.setForeground(new java.awt.Color(255, 255, 255));
        dos.setText("2");
        dos.setBorder(null);
        dos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dosActionPerformed(evt);
            }
        });
        Principal.add(dos, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 320, 60, 60));

        tres.setBackground(new java.awt.Color(102, 102, 102));
        tres.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        tres.setForeground(new java.awt.Color(255, 255, 255));
        tres.setText("3");
        tres.setBorder(null);
        tres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tresActionPerformed(evt);
            }
        });
        Principal.add(tres, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 320, 60, 60));

        menos.setBackground(new java.awt.Color(255, 153, 0));
        menos.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        menos.setForeground(new java.awt.Color(255, 255, 255));
        menos.setText("-");
        menos.setBorder(null);
        menos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menosActionPerformed(evt);
            }
        });
        Principal.add(menos, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 110, 60, 60));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Principal, javax.swing.GroupLayout.DEFAULT_SIZE, 374, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Principal, javax.swing.GroupLayout.DEFAULT_SIZE, 471, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void porActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_porActionPerformed
        // TODO add your handling code here:
        num1=Integer.parseInt(Result.getText());
        signo="*";
        Result.setText("");
    }//GEN-LAST:event_porActionPerformed

    private void unoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unoActionPerformed
        // TODO add your handling code here:
        Result.setText(Result.getText()+"1");
        
    }//GEN-LAST:event_unoActionPerformed

    private void dosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dosActionPerformed
        // TODO add your handling code here:
         Result.setText(Result.getText()+"2");
         
    }//GEN-LAST:event_dosActionPerformed

    private void menosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menosActionPerformed
        // TODO add your handling code here:
        num1=Integer.parseInt(Result.getText());
        signo="-";
        Result.setText("");
    }//GEN-LAST:event_menosActionPerformed

    private void ceroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ceroActionPerformed
        // TODO add your handling code here:
        Result.setText(Result.getText()+"0");
    }//GEN-LAST:event_ceroActionPerformed

    private void igualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_igualActionPerformed
        // TODO add your handling code here:
         num2 = Integer.parseInt(Result.getText());
        
        int resultado = Calculadora.calcular(num1, num2, signo);
        
        Result.setText(Integer.toString(resultado));
       
        
    }//GEN-LAST:event_igualActionPerformed

    private void masActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_masActionPerformed
        // TODO add your handling code here:
        num1=Integer.parseInt(Result.getText());
        signo="+";
        Result.setText("");
    }//GEN-LAST:event_masActionPerformed

    private void tresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tresActionPerformed
        // TODO add your handling code here:
         Result.setText(Result.getText()+"3");
    }//GEN-LAST:event_tresActionPerformed

    private void cuatroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cuatroActionPerformed
        // TODO add your handling code here:
         Result.setText(Result.getText()+"4");
    }//GEN-LAST:event_cuatroActionPerformed

    private void cincoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cincoActionPerformed
        // TODO add your handling code here:
         Result.setText(Result.getText()+"5");
    }//GEN-LAST:event_cincoActionPerformed

    private void seisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seisActionPerformed
        // TODO add your handling code here:
         Result.setText(Result.getText()+"6");
    }//GEN-LAST:event_seisActionPerformed

    private void sieteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sieteActionPerformed
        // TODO add your handling code here:
         Result.setText(Result.getText()+"7");
    }//GEN-LAST:event_sieteActionPerformed

    private void ochoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ochoActionPerformed
        // TODO add your handling code here:
         Result.setText(Result.getText()+"8");
    }//GEN-LAST:event_ochoActionPerformed

    private void nueveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nueveActionPerformed
        // TODO add your handling code here:
         Result.setText(Result.getText()+"9");
    }//GEN-LAST:event_nueveActionPerformed

    private void borrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borrarActionPerformed
        // TODO add your handling code here:
        Result.setText("");
    }//GEN-LAST:event_borrarActionPerformed

    private void dividirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dividirActionPerformed
        // TODO add your handling code here:
        num1=Integer.parseInt(Result.getText());
        signo="/";
        Result.setText("");
    }//GEN-LAST:event_dividirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CalculadoraFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CalculadoraFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CalculadoraFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CalculadoraFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CalculadoraFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Principal;
    private javax.swing.JLabel Result;
    private javax.swing.JButton borrar;
    private javax.swing.JButton cero;
    private javax.swing.JButton cinco;
    private javax.swing.JButton cuatro;
    private javax.swing.JButton dividir;
    private javax.swing.JButton dos;
    private javax.swing.JButton igual;
    private javax.swing.JButton mas;
    private javax.swing.JButton menos;
    private javax.swing.JButton nueve;
    private javax.swing.JButton ocho;
    private javax.swing.JButton por;
    private javax.swing.JButton seis;
    private javax.swing.JButton siete;
    private javax.swing.JButton tres;
    private javax.swing.JButton uno;
    // End of variables declaration//GEN-END:variables
}
